name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name:  restic-to-influxdb-x86_64-unknown-linux-gnu
        path: target/release/restic-to-influxdb
        repo-token: ${{ secrets.GITHUB_TOKEN }}
          

    
